Grey_MVC/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BLL;
using Contracts.Entities;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class ArticleController : Controller
    {
        private const int SidebarQuizId = 1,
            DefaultCountOfSimilarTags = 20,
            DefaultTagId = -1,
            DefaultCountOfSimilarArticles = 5;
        private readonly UnitOfLogic _unitOfLogic;

        public ArticleController()
        {
            _unitOfLogic = new UnitOfLogic();
        }
        // GET: Article
        public ActionResult Index(int tagId = DefaultTagId)
        {
            var articleEntities = _unitOfLogic.ArticleService.GetAll();
            
            var articleModels = articleEntities.Select(articleEntity => new ArticleModel
            {
                Id = articleEntity.Id,
                Author = articleEntity.Author.Name,
                Tags = articleEntity.Tags.Select(t=>new TagModel
                {
                    Id = t.Id,
                    Text = t.Text
                }),
                Text = articleEntity.Text,
                Title = articleEntity.Title,
                PublicationDate = articleEntity.PublicationDate
            })
                .OrderByDescending(a=>a.PublicationDate).ToList();

            if (tagId != DefaultTagId)
            {
                articleModels = articleModels.Where(a => a.Tags.
                    Select(t=>t.Id).Contains(tagId)).ToList();
            }

            ViewData["PopularTag"] = PopularTags(DefaultCountOfSimilarTags);
            var quiz = _unitOfLogic.QuizService.GetById(SidebarQuizId);
            ViewData["SidebarQuiz"] = new QuizModel
            {
                Id = quiz.Id,
                Title = quiz.Title,
                Questions = quiz.Questions.Select(q => new QuestionModel
                {
                    Id = q.Id,
                    NumberOfQuestion = q.NumberOfQuestion,
                    Text = q.Text,
                    Type = q.Type,
                    Variants = q.Variants.Select(v => new VariantModel
                    {
                        Id = v.Id,
                        Text = v.Text,
                        QuestionNumber = v.Question.NumberOfQuestion
                    })
                })
            };
            return View(articleModels);
        }
        
        public ActionResult Detail(int id)
        {
            var articleEntity = _unitOfLogic.ArticleService.GetById(id);
            var allComments = _unitOfLogic.CommentService.GetAll().Where(c => c.ArticleId == articleEntity.Id).ToList();
            var commentsModel = allComments.Select(c => new CommentModel()
            {
                Id = c.Id,
                ParentId = c.ParentId,
                LevelOfNesting = c.LevelOfNesting,
                Author = c.Author.Name,
                Date = c.Date,
                Text = c.Text
            }).ToList();
            foreach (var comment in commentsModel)
            {
                comment.ChildComments = commentsModel.Where(c => c.ParentId == comment.Id).ToList();
            }
            var articleModel = new ArticleModel
            {
                Id = articleEntity.Id,
                Author = articleEntity.Author.Name,
                PublicationDate = articleEntity.PublicationDate,
                Tags = articleEntity.Tags.Select(t => new TagModel
                {
                    Id = t.Id,
                    Text = t.Text
                }),
                Title = articleEntity.Title,
                Text = articleEntity.Text,
                Comments = commentsModel.Where(c=>c.ParentId==null).ToList()
            };
            ViewData["Similar"] = SimilarArticles(articleEntity, DefaultCountOfSimilarArticles);
            return View(articleModel);
        }

        [Authorize]
        public ActionResult Create()
        {
            ViewData["PopularTag"] = PopularTags(20);
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(ArticleModel newArticle)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }
            _unitOfLogic.ArticleService.Insert(new Article
            {
                Author = _unitOfLogic.UserService.GetCurrentUser(),
                PublicationDate = DateTime.UtcNow,
                Tags = newArticle.TagString != null ? _unitOfLogic.TagService.SplitToTags(newArticle.TagString) : null,
                Title = newArticle.Title,
                Text = newArticle.Text
            });
            _unitOfLogic.Save();
            return RedirectToAction("Index");
        }

        public IEnumerable<TagModel> PopularTags(int count)
        {
            return _unitOfLogic.TagService.GetPopular(count).
                Select(tag => new TagModel
                {
                    Id = tag.Id,
                    Text = tag.Text
                }).ToList();
        }

        public IEnumerable<ArticleModel> SimilarArticles(Article current,int count)
        {
            var similarArticles = _unitOfLogic.ArticleService.GetSimilar(current, count);
            return similarArticles?.Select(a => new ArticleModel()
            {
                Id = a.Id,
                Author = a.Author.Name,
                Title = a.Title
            });
        }

        [HttpPost]
        public ActionResult AddComment(CommentModel newComment)
        {
            _unitOfLogic.CommentService.Insert(new Comment()
            {
                ArticleId = newComment.ArticleId,
                Author = _unitOfLogic.UserService.GetCurrentUser(),
                Date = DateTime.UtcNow,
                LevelOfNesting = (newComment.ParentId != null)
                    ? _unitOfLogic.
                          CommentService.GetById(newComment.ParentId).LevelOfNesting + 1
                    : 0,
                ParentId = newComment.ParentId,
                Text = newComment.Text
            });
            return RedirectToAction("Detail", new {id = newComment.ArticleId});
        }
    }
}

Grey_MVC/Controllers/FeedbackController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using BLL;
using Contracts.Entities;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly UnitOfLogic _unitOfLogic;
        public FeedbackController()
        {
            _unitOfLogic = new UnitOfLogic();
        }


        public ActionResult Index()
        {
            var feedbackEntities = _unitOfLogic.FeedbackService.GetAll();
            var feedbackModels = feedbackEntities.
                Select(feedbackEntity => new FeedbackModel
                {
                Id = feedbackEntity.Id,
                Author = feedbackEntity.Author,
                PublicationDate = feedbackEntity.PublicationDate,
                Text = feedbackEntity.Text
            }).OrderByDescending(f=>f.PublicationDate).ToList();
            return View(feedbackModels);
        }
        [HttpPost]
        public ActionResult Index(FeedbackModel newFeedback)
        {
            _unitOfLogic.FeedbackService.Insert(new Feedback
            {
                Author = newFeedback.Author,
                PublicationDate = DateTime.UtcNow,
                Text = newFeedback.Text
            });
            _unitOfLogic.Save();
            return RedirectToAction("Index");
        }
    }
}

Grey_MVC/Controllers/QuizController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using BLL;
using Contracts.Entities;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class QuizController : Controller
    {
        private readonly UnitOfLogic _unitOfLogic;
        public QuizController()
        {
            _unitOfLogic = new UnitOfLogic();
        }

        [Authorize]
        public ActionResult Index()
        {
            var allQuiz = _unitOfLogic.QuizService.GetAll();
            var quizModel = allQuiz.Select(quizEntity => new QuizModel
            {
                Id = quizEntity.Id,
                Title = quizEntity.Title
            }).ToList();
            return View(quizModel);
        }
        [Authorize]
        public ActionResult Detail(int id)
        {
            var quiz = _unitOfLogic.QuizService.GetById(id);
            var quizModel = new QuizModel
            {
                Id = quiz.Id,
                Title = quiz.Title,
                Questions = quiz.Questions.Select(q => new QuestionModel
                {
                    Id = q.Id,
                    NumberOfQuestion = q.NumberOfQuestion,
                    Text = q.Text,
                    Type = q.Type,
                    Variants = q.Variants.Select(v => new VariantModel
                    {
                        Id = v.Id,
                        Text = v.Text,
                        QuestionNumber = v.Question.NumberOfQuestion
                    })
                })
            };
            return View(quizModel);
        }

        [HttpPost]
        public ActionResult Detail(FormCollection form)
        {
            GetStatisticData(form);
            SavePass(form);
            return RedirectToAction("Statistics", new { id = int.Parse(form["quizId"]) });
        }

        public ActionResult Statistics(int id)
        {
            var quiz = _unitOfLogic.QuizService.GetById(id);
            var countOfUsersPass = _unitOfLogic.
                QuizPassService.GetAll().Count(q => q.QuizId == id);
            var model = new QuizModel
            {
                Id = quiz.Id,
                Title = quiz.Title,
                Questions = quiz.Questions.Select(q => new QuestionModel
                {
                    Id = q.Id,
                    NumberOfQuestion = q.NumberOfQuestion,
                    Text = q.Text,
                    Variants = q.Variants.Select(v => new VariantModel
                    {
                        Id = v.Id,
                        Text = v.Text,
                        CountOfUse = v.CountOfUse,
                        PercentOfUsage = (int)(Math.Round((v.CountOfUse/(double)countOfUsersPass),2)*100)
                    })
                })
            };
            
            ViewBag.CountOfUsers = countOfUsersPass;
            return View(model);
        }

        private void GetStatisticData(FormCollection form)
        {
            var quiz = _unitOfLogic.QuizService.GetById(int.Parse(form["quizId"]));
            foreach (var question in quiz.Questions)
            {
                var answerText = form[question.NumberOfQuestion.ToString()];
                if (question.Type != QuestionType.Text)
                {
                    if (question.Type == QuestionType.SelectMultiple)
                    {
                        var answers = answerText.Split(',').ToList();
                        foreach (var singleAnswer in answers)
                        {
                            var variant = _unitOfLogic.VariantsService.GetAll().
                                First(v => v.QuestionId == question.Id && v.Text.Equals(singleAnswer));
                            variant.CountOfUse++;
                            _unitOfLogic.VariantsService.Update(variant);
                        }
                    }
                    else
                    {
                        var variant = _unitOfLogic.VariantsService.GetAll().
                            First(v => v.QuestionId == question.Id && v.Text.Equals(answerText));
                        variant.CountOfUse++;
                        _unitOfLogic.VariantsService.Update(variant);
                    }
                }
            }
            _unitOfLogic.Save();
        }
        private void SavePass(FormCollection form)
        {
            int quizId = int.Parse(form["quizId"]);
            Quiz quiz = _unitOfLogic.QuizService.GetById(quizId);
            QuizPass quizPass = new QuizPass
            {
                TitleOfQuiz = _unitOfLogic.QuizService.GetById(quizId).Title,
                AuthorId = _unitOfLogic.UserService.GetCurrentUser().Id,
                QuizId = quizId
            };
            _unitOfLogic.QuizPassService.Insert(quizPass);

            foreach (var question in quiz.Questions)
            {
                _unitOfLogic.AnswerService.Insert(new Answer
                {
                    QuizPassId = quizPass.Id,
                    Question = question.Text,
                    TextOfAnswer = form[question.NumberOfQuestion.ToString()]
                });
            }
            _unitOfLogic.Save();
        }
    }
}

Grey_MVC/Controllers/QuizPassController.cs
using System.Linq;
using System.Web.Mvc;
using BLL;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class QuizPassController : Controller
    {
        private readonly UnitOfLogic _unitOfLogic;
        public QuizPassController()
        {
            _unitOfLogic = new UnitOfLogic();
        }

        public ActionResult Index()
        {
            var quizPasses = _unitOfLogic.QuizPassService.GetAll().ToList();
            var quizPassModels = quizPasses.Select(quizPassEntity => new QuizPassModel
            {
                Id = quizPassEntity.Id,
                QuizTitle = quizPassEntity.TitleOfQuiz,
                Author = quizPassEntity.Author.Name,
                Answers = quizPassEntity.Answers.Select(a => new AnswerModel
                {
                    Id = a.Id,
                    Question = a.Question,
                    Answer = a.TextOfAnswer
                })
            }).ToList();
            return View(quizPassModels);
        }

        public ActionResult Detail(int id)
        {
            var quizPass = _unitOfLogic.QuizPassService.GetById(id);
            var quizPassModel = new QuizPassModel
            {
                Id = quizPass.Id,
                Author = quizPass.Author.Name,
                QuizTitle = quizPass.TitleOfQuiz,
                Answers = quizPass.Answers.Select(a=>new AnswerModel
                {
                    Id = a.Id,
                    Question = a.Question,
                    Answer = a.TextOfAnswer
                })
            };
            return View(quizPassModel);
        }
    }
}

Grey_MVC/Views/Shared/PartialSimilar.cshtml
@model IEnumerable<WebSite.Models.ArticleModel>
<p>Similar Articles</p>
@foreach (var article in Model)
{
    <p>@Html.ActionLink(article.Title, "Detail", "Article", new {article.Id}, null)</p>
}

Grey_MVC/Views/Shared/_GuestLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<div>
    <div class="row page-header" id="header">
        <div class="col-md-1">
            <img src="~/Content/images/logo.png" id="logo" style="width: 5vw; height:5vw" onclick="location.href='@Url.Action("Index","Article")'" />
        </div>
        <div class=" col-md-11 modal-title">
            <h2>Homework</h2>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 login">
                @RenderBody()
            </div>
        </div>
        <div class="col-md-12 modal-footer">
            &copy; GreyWolf @DateTime.Now.Year - <a href="#header">Back to top</a>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Grey_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="row page-header" id="header">
        <div class="col-md-1">
            <img src="~/Content/images/logo.png" id="logo" style="width: 5vw; height:5vw" onclick="location.href='@Url.Action("Index","Article")'" />
        </div>
        <div class=" col-md-11 modal-title">
            <h2>Homework</h2>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                @RenderBody()
            </div>
            <div class="col-md-3">
                <h3>Site Menu:</h3>
                <h4>@Html.ActionLink("Main", "Index", "Article")</h4>
                <h4>@Html.ActionLink("Feedbacks", "Index", "Feedback")</h4>
                <h4>@Html.ActionLink("Quizzes", "Index", "Quiz")</h4>
                <h4>@Html.ActionLink("Passes", "Index", "QuizPass")</h4>
                <hr/>
                <h4>@Html.ActionLink("Create new article","Create","Article")</h4>
                <hr/>
                @if (ViewData["PopularTag"] != null)
                {
                    <p>@Html.Partial("_PopularTags",ViewData["PopularTag"])</p>
                }
                @if (ViewData["SidebarQuiz"] != null)
                {
                    <hr/>
                    <div>@Html.Partial("_PartialQuiz",ViewData["SidebarQuiz"])</div>
                }
                @if (ViewData["Similar"] != null)
                {
                    <hr/>
                    <div>@Html.Partial("PartialSimilar",ViewData["Similar"])</div>
                }
            </div>
        </div>
        <div class="col-md-12 modal-footer">
            &copy; GreyWolf @DateTime.Now.Year - <a href="#header">Back to top</a>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Grey_MVC/Views/Shared/_PartialQuiz.cshtml
@using Contracts.Entities
@using GreyApplication.Helpers
@model WebSite.Models.QuizModel
<h4>Quiz</h4>
@using (Html.BeginForm("Detail","Quiz",FormMethod.Post))
{
    <input type="hidden" name="quizId" value="@Model.Id"/>
    foreach (var question in Model.Questions)
    {
        <p>
            @Html.DisplayFor(q => question.NumberOfQuestion).@Html.DisplayFor(q => question.Text)
        </p>
        switch (question.Type)
        {
            case QuestionType.Text:
                <input type="text",name="@question.NumberOfQuestion"/>
                break;
            case QuestionType.RadioButton:
                @Html.CreateRBList(question.Variants)
                break;
            case QuestionType.SelectOne:
                @Html.CreateComboBoxList(question.Variants, question.NumberOfQuestion)
                break;
            case QuestionType.SelectMultiple:
                @Html.CreateCheckBoxList(question.Variants)
                break;
        }
    }
    <input type="submit" value="Send"/>
}

Grey_MVC/Views/Shared/_PopularTags.cshtml
@model IEnumerable<WebSite.Models.TagModel>

<h4>Popular Tags</h4>
@foreach (var tag in Model)
{
    <span>@Html.ActionLink(tag.Text,"Index", "Article", new{tagId = tag.Id}, null) </span>
}